version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ledger_one_db
    environment:
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_password
      POSTGRES_DB: ledger_db
  
    volumes:
      - ledger_one_data_clean:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: ledger_one_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  ledger_one_data_clean:
